In [4]:
import pandas as pd

df = pd.read_csv("Estatisticas_Jogo.csv")

display(df)

  Jogador  Pontos
0  Miguel      15
1   Tiago      22
2     Rui      18
3   Artur      20

In [5]:
# Média de Pontos dos Jogadores

media_pontos = df["Pontos"].mean()

print(f"A média de pontos foi de {round(media_pontos, 1)} pontos")

A média de pontos foi de 18.8 pontos

In [6]:
# Jogador com mais pontos

mais_pontos = df["Pontos"].idxmax()

print(f"O jogador com mais pontos foi o {df.loc[mais_pontos, "Jogador"]} com {df.loc[mais_pontos, "Pontos"]} pontos")

O jogador com mais pontos foi o Tiago com 22 pontos

In [7]:
#Copiar o ficheiro estatisticas_jogo e colar/guardar dentro do ficheiro ranking_jogadores
df.to_csv("Ranking_Jogadores.csv", index=False)

df_ranking = pd.read_csv("Ranking_Jogadores.csv")

df_ranking.sort_values(by="Pontos", ascending=True, inplace=True)

df_ranking.to_csv("Ranking_Jogadores.csv", index=False)

display(df_ranking)

  Jogador  Pontos
0  Miguel      15
2     Rui      18
3   Artur      20
1   Tiago      22