In [8]:
import pandas as pd

df = pd.read_csv("Produtos.csv")

display(df)

   Produto  Preço  Quantidade  Valor Total
0  Teclado     20          15          300
1     Rato     10          30          300
2  Monitor    150           5          750

In [9]:
# Calcular valor Total de cada produto

df["Valor Total"] = df["Preço"] * df["Quantidade"]

df.to_csv("Produtos.csv", index=False)

In [15]:
# Encontar o produto mais caro

produto_maior = df["Preço"].idxmax()

display(f"O Produto mais caro é o {df.loc[produto_maior, "Produto"]} com o valor de {df.loc[produto_maior, "Preço"]} €")

'O Produto mais caro é o Monitor com o valor de 150 €'

In [19]:
# Ordenar Produtos por preço crescente

df.sort_values(by="Preço", ascending=True, inplace=True)

df.to_csv("Produtos.csv", index=False)

display(df)

   Produto  Preço  Quantidade  Valor Total
1     Rato     10          30          300
0  Teclado     20          15          300
2  Monitor    150           5          750